version: '3'
services:
  app:
    image: 559970378337.dkr.ecr.eu-central-1.amazonaws.com/tadeusz:latest
    command: main.js
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0-focal
    ports:
      - "27017:27017"
