name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Install dependencies
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install # will run `yarn install` command
        
    - name: Build an app
      uses: borales/actions-yarn@v2.3.0
      with:
          cmd: build # will run `yarn build` command
          
    - name: Run tests
      uses: borales/actions-yarn@v2.3.0
      with:
          cmd: test # will run `yarn test` command
    

